# depslib dependency file v1.0
1485841951 source:/home/jagveer/Documents/ECS40/HW1/IDE/FractionCalculator/main.cpp
	"Fraction.h"
	<iostream>
	<stdexcept>

1485842425 /home/jagveer/Documents/ECS40/HW1/IDE/FractionCalculator/Fraction.h
	<iostream>

